GET http://localhost:3000/subscribers
###
GET http://localhost:3000/subscribers/6068245d34082e267eee920b
###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "John Doe",
    "subscribeToChannel": "BBC"
}
###
DELETE http://localhost:3000/subscribers/6068245d34082e267eee920b
###
PATCH http://localhost:3000/subscribers/6068294d4bc0d02a578d4e85
Content-Type: application/json

{
    "name": "Jane Doe"
}